#!/usr/bin/env bash
cat <<'EOF'
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +72.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +65.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +60.0°C  (high = +80.0°C, crit = +100.0°C)
fan1:         1500 RPM
EOF
