#!/bin/bash

PREFIX=' '

get_load()
{
    local cpu_last=($(head -n1 /proc/stat))
    local cpu_last_sum="${cpu_last[@]:1}"
    cpu_last_sum=$((${cpu_last_sum// /+}))
    
    sleep 0.05
    
    local cpu_now=($(head -n1 /proc/stat))
    local cpu_sum="${cpu_now[@]:1}"
    cpu_sum=$((${cpu_sum// /+}))
    
    local cpu_delta=$((cpu_sum - cpu_last_sum))
    local cpu_idle=$((cpu_now[4] - cpu_last[4]))
    local cpu_used=$((cpu_delta - cpu_idle))
    
    if [[ $cpu_delta -eq 0 ]]; then
        echo "$PREFIX 0%"
        return
    fi
    
    local cpu_usage=$((100 * cpu_used / cpu_delta))
    
    echo "$PREFIX $cpu_usage%"
}

get_load
