#!/bin/bash

PREFIX=' '

get_day_percentage()
{
    local hour
    hour=$(date '+%H')
    local minute
    minute=$(date '+%M')
    local minutes=$((hour * 60 + minute))
    local percentage=$(((minutes * 100) / 1440))
    
    echo "$PREFIX$percentage%"
}

get_day_percentage
