#!/bin/bash

# Prints number of unread mail
# Requires mutt/neomutt

MAIL_DIR=${MAIL_DIR:-/home/$USER/Mail/INBOX/new}
PREFIX=' :'

get_mail() {
    shopt -s nullglob
    local files=("$MAIL_DIR"/*)
    echo "$PREFIX${#files[@]}"
}

get_mail
