#!/bin/bash

# Prints out your OS name

PREFIX=' '

get_os_name() {
    local name
    if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        name=${NAME:-}
    fi
    echo "$PREFIX${name}"
}

get_os_name
