#!/bin/bash

# Prints the total ram and used ram in Mb

PREFIX=' '

get_ram() {
    if ! command -v free >/dev/null 2>&1; then
        echo ""
        return 0
    fi
    USED_RAM=$(free | awk '/Mem/{printf("%d"), $3/$2*100}')
    echo "$PREFIX$USED_RAM%"
}

get_ram
