#!/bin/bash

# Gets temperature of the CPU
# Dependencies: lm_sensors

get_temperature()
{
	# CPU_T=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon?/temp2_input)
	# CPU_TEMP=$(expr $CPU_T / 1000)

	CPU_TEMP="$(sensors | grep temp1 | awk '{print $2}')"

	# elif [ "$CPU_TEMP" -le 10 ]; then
	# 	echo "  $CPU_TEMP"
	# else
	# 	echo " $CPU_TEMP"
	# fi
	echo " $CPU_TEMP"
}

get_temperature
