#!/bin/bash

# Prints the number of updates for Void Linux

PREFIX=' Updates: '

get_updates()
{
    if ! updates=$(xbps-install -Mun 2> /dev/null | wc -l ); then
        updates=0
    fi
    
    echo "$PREFIX$updates"
}

if [ $(( 10#$(date '+%M') % 3 )) -eq 0 ] && [ $(( 10#$(date '+%S') )) -eq 5 ]; then
    get_updates
fi
