#!/bin/bash

# Gets the wifi status

WIFI_FULL_ICON=''
WIFI_MID_ICON=''
WIFI_LOW_ICON=''
NO_WIFI_ICON=''

get_wifi() {
    local wireless_file=${WIRELESS_FILE:-/proc/net/wireless}
    [[ ! -f "$wireless_file" ]] && echo "$NO_WIFI_ICON" && return 0

    if grep -qE '^\s*w' "$wireless_file"; then
        local percentage
        percentage=$(grep -E '^\s*w' "$wireless_file" | awk '{ print int($3 * 100 / 70)}' | xargs)
        case $percentage in
            ''|0)                          echo "$NO_WIFI_ICON" ;;
            100|9[0-9]|8[0-9]|7[0-9])      echo "$WIFI_FULL_ICON" ;;
            6[0-9]|5[0-9]|4[0-9]|3[0-9])   echo "$WIFI_MID_ICON" ;;
            2[0-9]|1[0-9]|[0-9])           echo "$WIFI_LOW_ICON" ;;
        esac
    else
        echo "$NO_WIFI_ICON"
    fi
}

get_wifi
