#!/bin/bash

MODULES_DIR="/home/$USER/.config/dwmbar/modules/"

# What modules, in what order
MODULES="mpd weather volumebar wifi internet cpuload temperature date time"

# Modules that require an active internet connection
ONLINE_MODULES="weather internet"

# Delay between showing the status bar
DELAY="0.05"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beggining of the status bar
RIGHT_PADDING="$USER@$HOSTNAME "
LEFT_PADDING="  "
