#!/bin/bash

MODULES_DIR="modules/"

SEPARATOR=" | "

MODULES="volume temperature date time battery"

run_modules(){
	for module in $MODULES; do
		[[ ! "$OUTPUT" = "" ]] && OUTPUT="$OUTPUT$SEPARATOR"
		OUTPUT="$OUTPUT$(exec $MODULES_DIR$module)"
	done
}

run(){
	run_modules
	sleep 5; # Delays script before it's called again
	echo $OUTPUT
}

run
